" VimPlug setup

let data_dir = '~/.config/vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo ' . data_dir . '/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Install plugins at startup
" autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val:dir)')) | PlugInstall --sync | source $MYVIMRC endif

" Plugins

call plug#begin()

Plug 'airblade/vim-gitgutter'
Plug 'liuchengxu/vim-which-key'
Plug 'machakann/vim-sandwich'
Plug 'ntpeters/vim-better-whitespace'
Plug 'preservim/nerdtree'

call plug#end()

" Color scheme

" colorscheme iceberg

" Spell checker

autocmd FileType markdown setlocal spell

" Line numbers

:set number

:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
:  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
:augroup END

